### ISSUE TITLE
Turkish characters

### ISSUE THREAD

**Issue by melihbuyuk** [ChrisAU/Dawg#1]
Hi Chris,

In Turkish characters, it does not work. How is the problem?

This is the file : [turkish_raw.txt](https://github.com/ChrisAU/Dawg/files/614239/turkish_raw.txt)

Thanks...

**Comment by cjnevin** [comment]
Thanks for your interest in this project, I actually only ran the tests on French and English languages. I will need to try this out and get back to you about why it is having problems, my guess would be it has something to do with the character length being calculated incorrectly somewhere, since UTF8 characters can contain multiple bytes.

**Comment by cjnevin** [comment]
@melihbuyuk Please try the new version, it supports unicode characters.
